import numpy as np

from pfs.ga.common.config import Config

class SampleConfig(Config):
    def __init__(self,
                 obs_path: str = None,
                 pmap_path: str = None,
                 isochrones_path: str = None,
                 cut_nb: bool = False,
                 keep_blue: bool = False,
                 lp_member_limit: float = np.log(0.001),
                 gaia_crossmatch: bool = True,
                 gaia_crossmatch_radius: float = 0.1):
        
        # Path to the HSC data
        self.obs_path = obs_path

        # Path to the probability map generated by the PMap script
        self.pmap_path = pmap_path

        # Path to the isochrones
        self.isochrones_path = isochrones_path

        # Magnitude name mappings for the isochrones
        self.isochrones_name_mapping = {}

        # Use the NB515 filter to define the color cuts
        self.cut_nb = cut_nb

        # TODO
        self.keep_blue = keep_blue

        # Logarithm of the membership probability limit for members
        self.lp_member_limit = lp_member_limit
        
        self.gaia_crossmatch = gaia_crossmatch
        self.gaia_crossmatch_radius = gaia_crossmatch_radius      # arcsec

        super().__init__()