from .cobraangleflags import CobraAngleFlags
from .subarupfi import SubaruPFI
from .subaruwfc import SubaruWFC
from .subaruhsc import SubaruHSC
from .subarutelescope import SubaruTelescope
from .gaia import Gaia
from .cfht import CFHT
from .sdss import SDSS
from .ps1 import PS1